### ISSUE TITLE
Landing page block

### ISSUE THREAD

**Issue by aeffinidi** [atcheri/japantourguideagency.com-nextjs#1]
Préparer le logo du site

En gros, se référer et/ou cloner https://www.okujapan.com/

- [x] Barre de navigation
- [x] Hero zone
~~- [ ] Liens [instagram](https://www.instagram.com/tyj0520/
), facebook (youtube)~~
- [x] Features
- [x] Products
- [x] Témoignages: use trip advisor api key
- [x] Newsletter

**Comment by aeffinidi** [comment]
english only for the v1

**Comment by aeffinidi** [comment]
barre de navigation
![image](https://user-images.githubusercontent.com/86773100/235457361-1fe1e463-e1b4-4189-b999-aabb3c9fc695.png)

et bien entendu il faut que ça soit responsif

**Comment by aeffinidi** [comment]
la Hero zone.
Carousel faisant défiler une demie douzaine d'images
![image](https://user-images.githubusercontent.com/86773100/235458625-28814747-dbf6-4e50-80c7-20bd5e2275eb.png)

Avec un text retapé par chatGPT

**Comment by aeffinidi** [comment]
PArtie témoignages:

Obtenir le témoignage du guitariste du Dream Theatervia trust pilot ou autre serait un gros plus

**Comment by atcheri** [comment]
dans le style j'aime bien celui là:
https://builtatlightspeed.com/theme/ebazhanov-nextjs-tailwind-landing-page

**Comment by atcheri** [comment]
ou encore
https://builtatlightspeed.com/demo/chr-onicles-mountain-expedition-landing-page

**Comment by atcheri** [comment]
Add TripAdvisor icons and link to thé published comment
